development: 
  TWITTER_CONSUMER_KEY: 'XhijORkEUV16lxSfmzJTloV02'
  TWITTER_CONSUMER_SECRET: 'XDeDbZMNgmldPQbHzmg8AykxeINcrGxTkRrhruMekVQYMhZTib'
  TWITTER_ACCESS_TOKEN: '357623842-L61wG3PO4h6q6r6vCFyFaN1CVywop7UwjlAuC7HP'
  TWITTER_ACCESS_SECRET: 'qf2VEiPjJqasdKRaKWlT4ZUZ1uQvxKAwArQsPTwr5nXPG'
